exports.seed = function (knex, Promise) {
  var tblName = 'city';

  var countryRows =
    [
      { country_id: 1, country: 'Nepal', code: 'NP' }
    ];
  var rows = [
    { city: 'Kathmandu', country_id: 1 },
    { city: 'Pokhara', country_id: 1 },
    { city: 'Lalitpur', country_id: 1 },
    { city: 'Birganj', country_id: 1 },
    { city: 'Biratnagar', country_id: 1 },
    { city: 'Bharatpur', country_id: 1 },
    { city: 'Janakpur', country_id: 1 },
    { city: 'Hetauda', country_id: 1 },
    { city: 'Nepalganj', country_id: 1 },
    { city: 'Itahari', country_id: 1 },
    { city: 'Dharan', country_id: 1 },
    { city: 'Butwal', country_id: 1 },
    { city: 'Dhangadhi', country_id: 1 },
    { city: 'Budhanilkantha', country_id: 1 },
    { city: 'Gokarneshwar', country_id: 1 },
    { city: 'Bhimdatta', country_id: 1 },
    { city: 'Tilottama', country_id: 1 },
    { city: 'Tokha', country_id: 1 },
    { city: 'Birendranagar', country_id: 1 },
    { city: 'Kalaiya', country_id: 1 },
    { city: 'Tulsipur', country_id: 1 },
    { city: 'Chandragiri', country_id: 1 },
    { city: 'Madhyapur', country_id: 1 },
    { city: 'Bhaktapur', country_id: 1 },
    { city: 'Gadhimai', country_id: 1 },
    { city: 'Tarakeshwar', country_id: 1 },
    { city: 'Lahan', country_id: 1 },
    { city: 'Damak', country_id: 1 },
    { city: 'Banganga', country_id: 1 },
    { city: 'Attariya', country_id: 1 },
    { city: 'Lumbini', country_id: 1 },
    { city: 'Chandrapur', country_id: 1 },
    { city: 'Triyuga', country_id: 1 },
    { city: 'Ratnanagar', country_id: 1 },
    { city: 'Lekhnath', country_id: 1 },
    { city: 'Nagarjun', country_id: 1 },
    { city: 'Kirtipur', country_id: 1 },
    { city: 'Ghorahi', country_id: 1 },
    { city: 'Siddharthanagar', country_id: 1 },
    { city: 'Kohalpur', country_id: 1 },
    { city: 'Mahalakshmi', country_id: 1 },
    { city: 'Lamki', country_id: 1 },
    { city: 'Ghodaghodi', country_id: 1 },
    { city: 'Kageshwari', country_id: 1 },
    { city: 'Birtamod', country_id: 1 },
    { city: 'Siraha', country_id: 1 },
    { city: 'Mechinagar', country_id: 1 },
    { city: 'Gulariya', country_id: 1 },
    { city: 'Tikapur', country_id: 1 },
    { city: 'Kawasoti', country_id: 1 },
    { city: 'Khairahani', country_id: 1 },
    { city: 'Bansgadhi', country_id: 1 },
    { city: 'Gaidakot', country_id: 1 },
    { city: 'Belauri', country_id: 1 },
    { city: 'Rajapur', country_id: 1 },
    { city: 'Bhadrapur', country_id: 1 },
    { city: 'Barahathwa', country_id: 1 },
    { city: 'Shivaraj', country_id: 1 },
    { city: 'Pathari', country_id: 1 },
    { city: 'Bedkot', country_id: 1 },
    { city: 'Golbazar', country_id: 1 },
    { city: 'Kanchan', country_id: 1 },
    { city: 'Koshi', country_id: 1 },
    { city: 'Byas', country_id: 1 },
    { city: 'Dhangadimai', country_id: 1 },
    { city: 'Gauradaha', country_id: 1 },
    { city: 'Rapti', country_id: 1 },
    { city: 'Mirchaiya', country_id: 1 },
    { city: 'Sainamina', country_id: 1 },
    { city: 'Shani', country_id: 1 },
    { city: 'Dhanushadham', country_id: 1 },
    { city: 'Jaleshwar', country_id: 1 },
    { city: 'Punarwas', country_id: 1 },
    { city: 'Kapilvastu', country_id: 1 },
    { city: 'Chireshwarnath', country_id: 1 },
    { city: 'Devdaha', country_id: 1 },
    { city: 'Hariwan', country_id: 1 },
    { city: 'Jhalari', country_id: 1 },
    { city: 'Tripur', country_id: 1 },
    { city: 'Kamalamai', country_id: 1 },
    { city: 'Gorkha', country_id: 1 },
    { city: 'Ishwarpur', country_id: 1 },
    { city: 'Suryabinayak', country_id: 1 },
    { city: 'Sandhikharka', country_id: 1 },
    { city: 'Kankai', country_id: 1 },
    { city: 'Narayani', country_id: 1 },
    { city: 'Sunwal', country_id: 1 },
    { city: 'Shivasatakshi', country_id: 1 },
    { city: 'Garuda', country_id: 1 },
    { city: 'Nilkantha', country_id: 1 },
    { city: 'Dodhara', country_id: 1 },
    { city: 'Bajrabarahi', country_id: 1 },
    { city: 'Mahagadimai', country_id: 1 },
    { city: 'Kalika', country_id: 1 },
    { city: 'Dhankuta', country_id: 1 },
    { city: 'Pyuthan', country_id: 1 },
    { city: 'Shuklagandaki', country_id: 1 },
    { city: 'Rajbiraj', country_id: 1 },
    { city: 'Bhajani', country_id: 1 },
    { city: 'Karyabinayak', country_id: 1 },
    { city: 'Anantalingeshwar', country_id: 1 },
    { city: 'Madi', country_id: 1 },
    { city: 'Bardibas', country_id: 1 },
    { city: 'Sukhipur', country_id: 1 },
    { city: 'Krishnapur', country_id: 1 },
    { city: 'Rampur', country_id: 1 },
    { city: 'Gaur', country_id: 1 },
    { city: 'Nijgadh', country_id: 1 },
    { city: 'Urlabari', country_id: 1 },
    { city: 'Parashuram', country_id: 1 },
    { city: 'Chitrawan', country_id: 1 },
    { city: 'Ganeshman', country_id: 1 },
    { city: 'Bardaghat', country_id: 1 },
    { city: 'Lamahi', country_id: 1 },
    { city: 'Panchkhal', country_id: 1 },
    { city: 'Sharada', country_id: 1 },
    { city: 'Bherimalika', country_id: 1 },
    { city: 'Sundar', country_id: 1 },
    { city: 'Changunarayan', country_id: 1 },
    { city: 'Bheriganga', country_id: 1 },
    { city: 'Kusma', country_id: 1 },
    { city: 'Gaushala', country_id: 1 },
    { city: 'Belbari', country_id: 1 },
    { city: 'Mithila', country_id: 1 },
    { city: 'Devchuli', country_id: 1 },
    { city: 'Putalibazar', country_id: 1 },
    { city: 'Tansen', country_id: 1 },
    { city: 'Lalbandi', country_id: 1 },
    { city: 'Baglung', country_id: 1 },
    { city: 'Dullu', country_id: 1 },
    { city: 'Malangwa', country_id: 1 },
    { city: 'Shambhunath', country_id: 1 },
    { city: 'Bagchaur', country_id: 1 },
    { city: 'Besisahar', country_id: 1 },
    { city: 'Ramgram', country_id: 1 },
    { city: 'Melamchi', country_id: 1 },
    { city: 'Inaruwa', country_id: 1 },
    { city: 'Godawari', country_id: 1 },
    { city: 'Resunga', country_id: 1 },
    { city: 'Manthali', country_id: 1 },
    { city: 'Ramdhuni', country_id: 1 },
    { city: 'Rangeli', country_id: 1 },
    { city: 'Beni', country_id: 1 },
    { city: 'Panauti', country_id: 1 },
    { city: 'Madhyabindu', country_id: 1 },
    { city: 'Katari', country_id: 1 },
    { city: 'Bidur', country_id: 1 },
    { city: 'Babai', country_id: 1 },
    { city: 'Pokhariya', country_id: 1 },
    { city: 'Suryodaya', country_id: 1 },
    { city: 'Khandbari', country_id: 1 },
    { city: 'Dipayal', country_id: 1 },
    { city: 'Sanoshri', country_id: 1 },
    { city: 'Bhrikuti', country_id: 1 },
    { city: 'Duhabi', country_id: 1 },
    { city: 'Shankharapur', country_id: 1 },
    { city: 'Dudhauli', country_id: 1 },
    { city: 'Sabaila', country_id: 1 },
    { city: 'Banepa', country_id: 1 },
    { city: 'Phidim', country_id: 1 },
    { city: 'Chainpur', country_id: 1 },
    { city: 'Simraunghad', country_id: 1 },
    { city: 'Shubhaghat', country_id: 1 },
    { city: 'Dakshinkali', country_id: 1 },
    { city: 'Waling', country_id: 1 },
    { city: 'Beltar', country_id: 1 },
    { city: 'Letang', country_id: 1 },
    { city: 'Kolhabi', country_id: 1 },
    { city: 'Palungtar', country_id: 1 },
    { city: 'Bhimeshwar', country_id: 1 },
    { city: 'Mangalsen', country_id: 1 },
    { city: 'Mahamanjushri', country_id: 1 },
    { city: 'Amaragadhi', country_id: 1 },
    { city: 'Narayan', country_id: 1 },
    { city: 'Beldandi', country_id: 1 },
    { city: 'Thaha', country_id: 1 },
    { city: 'Dapcha', country_id: 1 },
    { city: 'Dhulikhel', country_id: 1 },
    { city: 'Saptakoshi', country_id: 1 },
    { city: 'Hanumannagar', country_id: 1 },
    { city: 'Api', country_id: 1 },
    { city: 'Sundarbazar', country_id: 1 },
    { city: 'Krishnanagar', country_id: 1 },
    { city: 'Jayaprithvi', country_id: 1 },
    { city: 'Buddhabatika', country_id: 1 },
    { city: 'Patan', country_id: 1 },
    { city: 'Myanglung', country_id: 1 },
    { city: 'Ilam', country_id: 1 },
    { city: 'Taplejung', country_id: 1 },
    { city: 'Chandannath', country_id: 1 },
    { city: 'Rainas', country_id: 1 },
    { city: 'Musikot', country_id: 1 },
    { city: 'Bhanu', country_id: 1 },
    { city: 'Sanphebagar', country_id: 1 },
    { city: 'Badimalika', country_id: 1 },
    { city: 'Bhirkot', country_id: 1 },
    { city: 'Pakhribas', country_id: 1 },
    { city: 'Diktel', country_id: 1 },
    { city: 'Dasharathchand', country_id: 1 },
    { city: 'Laliguras', country_id: 1 },
    { city: 'Siddhicharan', country_id: 1 },
    { city: 'Anbu', country_id: 1 },
    { city: 'Bhojpur', country_id: 1 },
    { city: 'Kamalbazar', country_id: 1 },
    { city: 'Chautara', country_id: 1 },
    { city: 'Bandipur', country_id: 1 },
    { city: 'Chaurjahari', country_id: 1 },
    { city: 'Madi', country_id: 1 },
    { city: 'Jiri', country_id: 1 },
    { city: 'Liwang', country_id: 1 },
    { city: 'Shadanand', country_id: 1 },
    { city: 'Chapakot', country_id: 1 },
    { city: 'Ramechhap', country_id: 1 },
    { city: 'Dudhkunda', country_id: 1 },
    { city: 'Deumai', country_id: 1 },
    { city: 'Madhyanepal', country_id: 1 },
    { city: 'Fulgama', country_id: 1 }
  ];

  return knex('country')
    .del()
    .then(function () {
      return knex.insert(countryRows).into('country')
        .then(
        function () {
          return knex(tblName)
            .del()
            .then(function () {
              return knex.insert(rows).into(tblName);
            });
        }
        );
    });

};
